name: 🚀 Fake Deployment

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build number"
        required: true

  workflow_run:
    workflows:
      - Go
    types:
      - completed
    branches:
      - main

jobs:
  auto-deploy:
    name: "Auto Deploy"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deployed ${{ github.event.workflow_run.run_number }}"

  manual-deploy:
    name: "Manual Deploy"
    if: ${{ github.event.inputs.build_number != null }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deployed ${{ github.event.inputs.build_number }}"
