name: Fake Deployment

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build number"
        required: true

env:
  RUN_NUMBER: ${{ github.run_number }}
  RUN_NUMBER_WITH_OFFSET: $(($RUN_NUMBER+1000))

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deployed ${{ github.event.inputs.build_number }}"

      - run: echo "run number with offset ${{ env.RUN_NUMBER_WITH_OFFSET }}"
