name: 🚀 Fake Deployment

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build number"
        required: true

  workflow_run:
    workflows:
      - Go
    types:
      - completed
    branches:
      - main

env:
  BUILD_NUMBER: ${{ github.event.inputs.build_number || github.event.workflow_run.run_number }}

jobs:
  deploy:
    if: ${{ github.event.inputs.build_number || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deployed ${{ env.BUILD_NUMBER }}"

      - name: annotation
        uses: actions/github-script@v4
        with:
          script: core.notice('deployed ${{ env.BUILD_NUMBER }}')
