name: Test

on:
  workflow_dispatch:
    inputs:
      build_number:
        type: number
        description: "Build number"
        required: true
      project:
        description: "Project"
        required: true
        default: "front"
        type: choice
        options:
          - front

  workflow_call:
    inputs:
      build_number:
        type: number
        description: "Build number"
        required: true
      project:
        description: "Project"
        required: true
        default: "front"
        type: choice
        options:
          - front
jobs:
  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"
